# Railway Configuration for futStats (Project Root)

# Force Railway to use Docker instead of Nixpacks
[build]
builder = "dockerfile"
dockerfilePath = "server/Dockerfile"

# Deploy configuration
[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables (set these in Railway dashboard)
# DATABASE_URL=postgresql://...
# PORT=8080
# SECRET_KEY=your-secret-key
# ENVIRONMENT=production
# ALLOWED_ORIGINS=https://your-frontend-domain.com
