# Railway Configuration for futStats
# This file should be in the project root

[build]
builder = "dockerfile"
dockerfilePath = "server/Dockerfile"
buildContext = "server"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
