# Root configuration
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Arguments passed to the Go binary during build
  args_bin = []
  
  # Path for the built binary
  bin = "./tmp/main"
  
  # Command to build the application
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  
  # Delay before restarting after file changes (in milliseconds)
  delay = 1000
  
  # Directories to exclude from watching
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  
  # Specific files to exclude from watching
  exclude_file = []
  
  # Regular expressions to exclude certain files
  exclude_regex = ["_test.go"]
  
  # Restart only if watched files are changed (default is false)
  exclude_unchanged = false
  
  # Follow symbolic links (default is false)
  follow_symlink = false
  
  # Optional full binary path (if needed)
  full_bin = ""
  
  # Directories to include in file watching
  include_dir = ["./cmd", "./internal"]
  
  # File extensions to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
  
  # Delay before killing the old process after a rebuild
  kill_delay = "0s"
  
  # Path to the log file for build errors
  log = "build-errors.log"
  
  # Send an interrupt signal to stop the old process (default is false)
  send_interrupt = false
  
  # Stop rebuilding on the first error (default is true)
  stop_on_error = true

[color]
  app = ""       # Color for the app logs
  build = "yellow" # Color for build logs
  main = "magenta" # Color for main logs
  runner = "green" # Color for runner logs
  watcher = "cyan" # Color for watcher logs

[log]
  time = true    # Include timestamps in logs

[misc]
  clean_on_exit = true # Clean up the temporary directory on exit

[screen]
  clear_on_rebuild = true # Clear the screen on rebuild
