# Nixpacks configuration for futStats
# This is an alternative to Dockerfile for Railway

[phases.setup]
nixPkgs = ["go_1_23"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -o main ./cmd/main.go"]

[start]
cmd = "./main"

[variables]
PORT = "8080"
